/**
 * Module Dependencies
 */

var minstache = require('minstache');

var preload = [
  "/** ",
  "* WARNING: Do not edit this file directly!  Use `options['web-preferences'].preload` to add your preload settings.",
  "*/",

  "window.__nightmare = {};",
  "__nightmare.ipc = require('ipc');",
  "__nightmare.sliced = require('sliced');",

  "window.addEventListener('error', function(e) {",
  "  __nightmare.ipc.send('page', 'error', e.message, e.error.stack);",
  "});",

  "(function(){",
  "  var defaultLog = console.log;",
  "  console.log = function() {",
  "    __nightmare.ipc.send('page', 'log', arguments);",
  "    return defaultLog.apply(this, arguments);",
  "  };",

  "  var defaultAlert = window.alert;",
  "  window.alert = function(message){",
  "    __nightmare.ipc.send('page', 'alert', message);",
  "  };",

  "  var defaultPrompt = window.prompt;",
  "  window.prompt = function(message, defaultResponse){",
  "    __nightmare.ipc.send('page', 'prompt', message, defaultResponse);",
  "    throw new Error('prompt not overridden');",
  "  };",

  "  var defaultConfirm = window.confirm;",
  "  window.confirm = function(message){",
  "    __nightmare.ipc.send('page', 'confirm', message);",
  "    throw new Error('confirm not overridden');",
  "  };",
  
  "  {{!src}}",
  "})()"
].join('\n');

exports.preload = minstache.compile(preload);
